package:
  name: netgen4smesh
  version: 5.3.1

source:
  path: ../..

build:
  detect_binary_files_with_prefix: True
  number: 1
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - ninja
    - cmake
    - oce ==0.18.1

  run:
    - oce ==0.18.1

about:
  home: https://github.com/tpaviot/netgen4smesh
  license: LGPLv2.1
  summary: The netgen-mesher tuned to be used as an smesh mesher plugin.
