include(D:/Devel/netgen-mesher-git/cmake/netgen_fixup.cmake)
set(APP C:/netgen)
message(${APP})
set(BU_CHMOD_BUNDLE_ITEMS ON)

file(GLOB libs C:/netgen/lib/*.dylib C:/netgen/lib/*.so)
message("${libs}")
netgen_fixup_bundle( ${APP}/Contents/MacOS/netgen "${libs}" C:/netgen/lib )
execute_process(COMMAND ln -s /Applications C:/netgen/../Applications)
set (bundle_filename $ENV{NETGEN_BUNDLE_NAME})
if(NOT bundle_filename)
  set(bundle_filename netgen)
endif(NOT bundle_filename)
execute_process(COMMAND hdiutil create -volname Netgen -srcfolder C:/netgen -ov -format UDZO ${bundle_filename}-6.2-17243.dmg)
